apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedoom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedoom
  template:
    metadata:
      labels:
        app: kubedoom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
        - name: kubedoom
          image: storaxdev/kubedoom:0.5.0
          ports:
            - protocol: TCP
            - containerPort: 5900
  namespace: kubedoom
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    labels:
      app: kubedoom
    name: kubedoom
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
  subjects:
    - kind: ServiceAccount
      name: kubedoom
      namespace: kubedoom