apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  # serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres 
    spec:
      containers:
        - name: postgres
          image: postgres:10.13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: testdatabase
            - name: POSTGRES_USER
              value: testuser
            - name: POSTGRES_PASSWORD
              # value: testpassword
              valueFrom: 
                secretKeyRef:
                  name: my-secret
                  key: PASS
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: pgdata
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pvc
