apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  # serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres 
    spec:
      containers:
        - image: postgres:10.13
          name: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: testdatabase
            - name: POSTGRES_USER
              value: testuser
            - name: POSTGRES_PASSWORD
              # value: testpassword
              valueFrom: 
                secretKeyRef:
                  name: my-secret
                  key: PASS
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: pgdata
        - image: redmine:4.1.1
          name: redmine
          ports:
            - containerPort: 3000
          env:
            - name: REDMINE_DB_POSTGRES
              value: database
            - name: REDMINE_DB_USERNAME
              value: testuser
            - name: REDMINE_DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: my-secret
                  key: PASS
            - name: REDMINE_DB_DATABASE
              value: redminedatabase
            - name: REDMINE_SECRET_KEY_BASE
              valueFrom: 
                secretKeyRef:
                  name: my-super-secret
                  key: PASS
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pvc
