apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    service: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redmine
spec:
  selector:
    service: redmine
  ports:
  - port: 3000
